name: Node Test for PRs

on:
  pull_request:
    branches:
      - development
      - staging
      - "release/*"
      - main

jobs:
  test:
    name: Install dependencies, test, and deploy a PR build
    runs-on: ubuntu-latest
    env:
      aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}-pr-${{ github.event.number }}
    strategy:
      matrix:
        node: ["14"]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: npm i
      - run: npm run test
      - name: Build
        run: npm run build
      - uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./build/reports/jest/lcov.info
